### ISSUE TITLE
upgrade to cucumber 2.3 & pitest plugin 1.3

### ISSUE THREAD

**Issue by tyrcho** [alexvictoor/pitest-cucumber-plugin#16]
Hi @alexvictoor , long time since ENSEEIHT ;)

Would you please upgrade this cool plugin to latest versions ? I tried quick hacks but did not succeed to make this work with latest releases.

**Comment by alexvictoor** [comment]
Hello :)
Indeed quite a long time, hope you are doing well. Unfortunately I am quite busy these days so I cannot guarantee anything. Maybe we should do the update in two steps, handle cucumber & pitest upgrades independently. If you can send me a PR for one of those two it would help.

**Comment by tyrcho** [comment]
same here, I make no promises, time is short at the moment and I have no experience about this kind of plugin yet.

**Comment by alexvictoor** [comment]
Hello @tyrcho 
I guess we can close this issue?
Happy new year btw ;)

**Comment by tyrcho** [comment]
Hi alex, sure, no problem ...
