### ISSUE TITLE
crashing when using Cucumber 1.2.0, getting NoClassDefFoundError

### ISSUE THREAD

**Issue by vincent-fuchs** [alexvictoor/pitest-cucumber-plugin#4]
Hi,

I'm using Cucumber jvm 1.2.0 on my project, and when using the PIT plugin, it's crashing, because of NoClassDefFoundError.

```
10:08:11 AM PIT >> INFO : SLAVE : 10:08:11 AM PIT >> SEVERE : Error calculating coverage. Process will exit.
java.lang.NoClassDefFoundError: cucumber/api/junit/Cucumber$Options
        at org.pitest.cucumber.CucumberTestUnitFinder.findTestUnits(CucumberTestUnitFinder.java:25)
        at org.pitest.ju
10:08:11 AM PIT >> SEVERE : Coverage generator Slave exited abnormally due to UNKNOWN_ERROR
```
It looks like this class has been removed from latest version of Cucumber. When downgrading to 1.1.8 (the same version referenced in the plugin pom.xml), it worked fine. I think all is needed is l.25 in CucumberTestUnitFinder to remove the search for Cucumber.Options.class , which doesn't exist anymore, ie :

```
RuntimeOptionsFactory runtimeOptionsFactory = new RuntimeOptionsFactory(junitTestClass, new Class[]{CucumberOptions.class});
```

instead of 

```
RuntimeOptionsFactory runtimeOptionsFactory = new RuntimeOptionsFactory(junitTestClass, new Class[]{CucumberOptions.class, Cucumber.Options.class});
```

**Comment by alexvictoor** [comment]
Thanks a lot for your feedback
I will try to fix it asap

**Comment by alexec** [comment]
+1 also on 1.2.2

**Comment by vincent-fuchs** [comment]
This can be closed as Alex has fixed it in https://github.com/alexvictoor/pitest-cucumber-plugin/pull/5/
